; Generated by AutoGUI 2.5.4
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Add, Text, x41 y20 w120 h20 +0x200, From folder
Gui Add, Edit, x120 y20 w250 h20
Gui Add, Button, x416 y20 w80 h20, browse

Gui Add, Text, x41 y50 w120 h20 +0x200, To folder
Gui Add, Edit, x120 y50 w250 h20
Gui Add, Button, x416 y50 w80 h20, browse

Gui Add, Text, x41 y80 w120 h20 +0x200, Format
Gui Add, Edit, x120 y80 w181 h20

Gui Add, Button, x41 y110 w80 h20, GO

Gui Show, w1022 h544, Window
Return

GuiEscape:
GuiClose:
    ExitApp
